project:
  type: book

book:
  title: "aMeta Workshop"
  reader-mode: true
  repo-url: https://github.com/kirdoklab/aMeta-workshop
  site-url: kirdoklab.gitub.io/aMeta-workshop/

  author: "Zoe Pochon, Nora Bergfeldt, Emrah Kırdök"
  date: "30/01/2023"
  chapters:
    - href: index.qmd
      text: Home
    - part: organization.md
      chapters:
        - href: info-mersin.md
          text: "Information about the place"
        - href: about.qmd
          text: "About the team"
        - href: cluster-connection.qmd
          text: "Computing details"
    - href: course-style.qmd
      text: "How to follow the course?"
    - href : qc.qmd
      text: "Quality Control Step"
    - href: krakenuniq.md
      text: "KrakenUniq Step"
    - href: align.md
      text: "Bowtie2 Step"
    - href: damage.md
      text: "MapDamage"
    - href: summary.md
      text: "Summarizing the results"
    - href: references.qmd
      text: "References"


bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    pdf:
      documentclass: scrreprt



