project:
  type: book

book:
  title: "."
  author: "Emrah Kırdök, Ph.D."
  date: "30/01/2023"
  chapters:
    - href: index.qmd
      text: Home
    - about.qmd


format:
  html:
    theme: cosmo
    pdf:
      documentclass: scrreprt



