project:
  type: book

book:
  title: "aMeta Workshop"
  author: "Emrah Kırdök, Ph.D."
  date: "30/01/2023"
  chapters:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: "About the team"


format:
  html:
    theme: cosmo
    pdf:
      documentclass: scrreprt



