project:
  type: book

book:
  title: "aMeta Workshop"
  reader-mode: true
  repo-url: https://github.com/kirdoklab/aMeta-workshop
  site-url: kirdoklab.gitub.io/aMeta-workshop/

  author: "Zoe Pochon, Nora Bergfeldt, Emrah Kırdök"
  date: "30/01/2023"
  chapters:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: "About the team"
    - href: cluster-connection.md
      text: "Computing details"
    - href: course-style.qmd
      text: "How to follow the course?"
    - href : qc.qmd
      text: "Quality Control Step"
    - href: krakenuniq.md
      text: "KrakenUniq Step"
    - href: align.md
      text: "Bowtie2 Step"
    - href: references.qmd
      text: "References"

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    pdf:
      documentclass: scrreprt



