project:
  type: book

book:
  title: "aMeta Workshop"
  reader-mode: true
  repo-url: https://github.com/kirdoklab/aMeta-workshop
  site-url: kirdoklab.gitub.io/aMeta-workshop/

  author: "Zoé Pochon, Nora Bergfeldt, Emrah Kırdök"
  date: "30/01/2023"
  chapters:
    - href: index.qmd
      text: Home
    - href: course-style.qmd
      text: "Understand snakemake"
    - href: rulegraph.md
      text: "aMeta workflow graph"
    - part: "NEOMATRIX Workshop"
      chapters:
        - href: info-mersin.md
          text: "Information about the place"
        - href: about.qmd
          text: "About the team"
        - href: cluster-connection.qmd
          text: "How to connect to servers?"
        - href: course-setup.qmd
          text: "Course setup"
    - part: "The main pipeline"
      chapters:
        - href : qc.qmd
          text: "Quality Control Step"
        - href: krakenuniq.md
          text: "KrakenUniq Step"
        - href: malt.md
          text: "Malt step"
        - href: summary.md
          text: "Summarizing the results"
    - part: "The accessory pipeline"
      chapters:
        - href: align.md
          text: "Bowtie2 Step"
        - href: damage.md
          text: "MapDamage step"
    - href: aMeta-pipeline-setup.md
      text: "aMeta snakemake setup"
    - href: references.qmd
      text: "References"


bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    pdf:
      documentclass: scrreprt



