project:
  type: book

book:
  title: "aMeta Workshop"
  reader-mode: true
  
  author: "Emrah Kırdök, Ph.D."
  date: "30/01/2023"
  chapters:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: "About the team"
    - href: course-style.qmd
      text: "How to follow the course?"
    - href : qc.qmd
      text: "Quality Control Step"
    - href: krakenuniq.md
      text: "KrakenUniq Step"


format:
  html:
    theme: cosmo
    pdf:
      documentclass: scrreprt



