---
title: "About"
---

## About this website

This website was built for the aMeta Neomatrix workshop, taking place in Mersin Feb 6 – 10 2023.

## The team

### Emrah Kırdök
[Emrah Kırdök](https://scholar-google-se.ezp.sub.su.se/citations?user=BUj9itoAAAAJ&hl=sv&oi=ao) is an assistant professor at Mersin University. 

Emrah's research focuses on understanding human history through ancient DNA (aDNA). Generally, a little proportion of aDNA sequences could be mapped to its host reference genome. The remaining fragments come either from the microbiome of the ancient host or the environment that encapsulates the host.

By analyzing the remaining aDNA sequences with the state-of-the-art metagenomic methods it's possible to (i) construct the microbiome composition of ancient humans, (ii) reconstruct the ancient pathogenic genomes, (iii) understand the evolutionary mechanisms of the ancient pathogens.


### Zoé Pochon

[Zoé](http://palaeogenetics.com/zp/) started her PhD in Scientific archaeology at the Centre for Palaeogenetics, in Stockholm, in 2021. Zoé was trained in both biology and history and is interested in using archaeogenetics to bring new clues to debates on historical and biological questions. Her current work focuses on using bioinformatics tools to analyse the DNA (and hopefully one day RNA) of ancient viruses, as well as other microbes to get a better picture of the common pathogens at different time periods in history and to help understand past epidemics. Some of her former research projects have included the demographic analysis of combatants from a Bronze Age battlefield and the estimate of the selection coefficient of the lactase persistence, an allelic mutation already present in some of them. 


### Nora Bergfeldt

[Nora](http://palaeogenetics.com/nora-bergfeldt-2/) started her PhD in Zoology at the Centre for Palaeogenetics in 2019. She has a background in ecology, biodiversity and genomics. Her research focuses on using metagenomic tools to study bacteria and other microbes in ancient humans, with a particular interest in studying the evolution of pathogens.
